name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install deps
      run: sudo apt-get install -y libboost-all-dev libjsoncpp-dev antlr3.2 libantlr3c-dev minisat

    - name: configure
      run: ./setup.sh

    - name: make
      run: make

