name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: apt-install libboost-dev && ./setup.sh
    - name: make
      run: make

